In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [35]:
def contraction(delta,p,beta,x):
    #beta and x are kind of parameters. x is the empirical distribution of x?
    return (np.exp(delta*p+beta*x)/(1+np.exp(delta*p+beta*x))).mean(axis=0)

ps = np.array([1, 0])
deltas =  np.array([-2, -2])
betas = np.array([1, 1])
xs = np.random.normal(scale=2, size=(1000,2)) #assumes xs are independent? could use a copula?

print(contraction(deltas,ps,betas,xs))

[0.2180611  0.49536045]


In [36]:
def contraction_map(delta,p,beta,x):
    """final result is beliefs of firm1/firm2"""
    for i in range(20):
        #print('b1: %.4f, p2: %.4f'%tuple(p))
        p = contraction(delta,p,beta,x)
        p = np.flip(p)
        #print('p1: %.4f, p2: %.4f'%tuple(p))
        #print('----- end of iteration %s ----'%i)
    return p

result = contraction_map(deltas,ps,betas,xs)
print(result)

[0.37954973 0.38507806]


In [37]:
#actually caclualte an equilibrium in this game
us = np.random.logistic(size=(1000,2))
ys = ( (deltas*result + betas*xs + us) >=0 ).astype(int)
print(ys.sum(axis=0)/1000)

[0.375 0.412]


In [38]:
print(np.concatenate( (ys,xs ) ,axis=1))

[[ 0.          1.          0.36623034  2.86029817]
 [ 0.          0.         -0.45379263 -2.15397429]
 [ 0.          0.         -1.348806    0.85871343]
 ...
 [ 0.          0.         -2.58206671  0.88452194]
 [ 1.          0.          1.05818777 -2.37293872]
 [ 1.          1.          0.99022009  1.85173192]]
