In [1]:
%load_ext autoreload
%autoreload 2

import numpy as np
import pandas as pd
import datetime
#graphing
import matplotlib.pyplot as plt
#stats
import statsmodels.api as sm
from statsmodels.base.model import GenericLikelihoodModel

#import testing
import sys
sys.path.append("../")
import selection_tests

In [2]:
entry_data = pd.read_csv("../data/merged_entry.csv")
entry_data.loc[entry_data['HD'] > 0.0, 'HD_1'] = 1
entry_data.loc[entry_data['LO'] > 0.0, 'LO_1'] = 1
entry_data['income_2'] = np.log(1 + entry_data['income_per_capita'])
entry_data['population_2'] = np.log(1 + entry_data['population'])
entry_data = entry_data.fillna(0)

/home/erichschulman/anaconda3/lib/python3.9/site-packages/pandas/core/arraylike.py:364: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [3]:
# Fit the NashLogit model
x = entry_data[['income_2','population_2','income_2','population_2']].copy()
y = entry_data[['HD_1','LO_1']]
NashLogit_model = selection_tests.NashLogit(y,x).fit(xtol=1e-6,ftol=1e-6)
NashLogit_model.summary()

Optimization terminated successfully.
         Current function value: 0.416220
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.520699
         Iterations 7
[-0.14254449  0.50316223 -0.13063233  0.42585139 -3.37383234 -3.33023913]


/home/erichschulman/anaconda3/lib/python3.9/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


<class 'statsmodels.iolib.summary.Summary'>
"""
                              NashLogit Results                               
==============================================================================
Dep. Variable:       ['HD_1', 'LO_1']   Log-Likelihood:                -2338.3
Model:                      NashLogit   AIC:                             4681.
Method:            Maximum Likelihood   BIC:                             4692.
Date:                Mon, 09 May 2022                                         
Time:                        21:53:28                                         
No. Observations:                2155                                         
Df Residuals:                    2153                                         
Df Model:                           1                                         
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
income_2        -0.1481      0.040     -3.717      0.000      -0.226      -0.070
population_2     0.3672      0.051      7.160      0.000       0.267       0.468
income_2        -0.1498      0.039     -3.809      0.000      -0.227      -0.073
population_2     0.3603      0.046      7.859      0.000       0.270       0.450
par0            -1.4407      0.442     -3.260      0.001      -2.307      -0.575
par1            -2.2686      0.399     -5.691      0.000      -3.050      -1.487
================================================================================
"""

In [4]:
# Fit the BayesNashLogit model
x = entry_data[['income_2','population_2','income_2','population_2']].copy()
y = entry_data[['HD_1','LO_1']]
BayesNashLogit_model = selection_tests.BayesNashLogit(y,x).fit(xtol=1e-6,ftol=1e-6)
BayesNashLogit_model.summary()

Optimization terminated successfully.
         Current function value: 0.416220
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.520699
         Iterations 7
[-0.14254449  0.50316223 -0.13063233  0.42585139 -3.37383234 -3.33023913]


/home/erichschulman/anaconda3/lib/python3.9/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


<class 'statsmodels.iolib.summary.Summary'>
"""
                            BayesNashLogit Results                            
==============================================================================
Dep. Variable:       ['HD_1', 'LO_1']   Log-Likelihood:                -2680.0
Model:                 BayesNashLogit   AIC:                             5364.
Method:            Maximum Likelihood   BIC:                             5375.
Date:                Mon, 09 May 2022                                         
Time:                        21:53:31                                         
No. Observations:                2155                                         
Df Residuals:                    2153                                         
Df Model:                           1                                         
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
income_2        -0.2296      0.038     -5.984      0.000      -0.305      -0.154
population_2     0.3090      0.042      7.317      0.000       0.226       0.392
income_2        -0.2140      0.035     -6.147      0.000      -0.282      -0.146
population_2     0.2164      0.038      5.674      0.000       0.142       0.291
par0             0.6386      0.258      2.473      0.013       0.133       1.145
par1             0.3262      0.232      1.405      0.160      -0.129       0.781
================================================================================
"""

In [5]:
# Fit the regular test model
x = entry_data[['income_2','population_2','income_2','population_2']].copy()
y = entry_data[['HD_1','LO_1']]
regular_test_model = selection_tests.regular_test(y,x,selection_tests.setup_test)
regular_test_model

Optimization terminated successfully.
         Current function value: 0.416220
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.520699
         Iterations 7
[-0.14254449  0.50316223 -0.13063233  0.42585139 -3.37383234 -3.33023913]
Optimization terminated successfully.
         Current function value: 0.416220
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.520699
         Iterations 7
[-0.14254449  0.50316223 -0.13063233  0.42585139 -3.37383234 -3.33023913]


/home/erichschulman/anaconda3/lib/python3.9/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


regular: test, llr, omega ----
14.484980481263007 341.69165948891765 0.5081510490135205
---- 


(1, 14.484980481263007)

In [6]:
# Fit the bootstrap test model
x = entry_data[['income_2','population_2','income_2','population_2']].copy()
y = entry_data[['HD_1','LO_1']]
bootstrap_test_model = selection_tests.bootstrap_test(y,x,selection_tests.setup_test, trials=100)
bootstrap_test_model

Optimization terminated successfully.
         Current function value: 0.416220
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.520699
         Iterations 7
[-0.14254449  0.50316223 -0.13063233  0.42585139 -3.37383234 -3.33023913]
Optimization terminated successfully.
         Current function value: 0.416220
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.520699
         Iterations 7
[-0.14254449  0.50316223 -0.13063233  0.42585139 -3.37383234 -3.33023913]


/home/erichschulman/anaconda3/lib/python3.9/site-packages/statsmodels/base/model.py:566: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "


(1, 11.255913530611522, 17.47043877488168)